apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-test-7
  labels:
    app: netshoot-1
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|default|netshoot-1
  namespace: ns-netshoot-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot-1
  template:
    metadata:
      labels:
        app: netshoot-1
    spec:
      containers:
      - name: netshoot-test-7
        image: nicolaka/netshoot
        command:
        - /bin/bash
        args:
        - "-c"
        - while true; do ping localhost; sleep 60;done
